import { count } from "drizzle-orm";
import { db } from "@workspace/db";
import { clubsTable, eventsTable } from "@workspace/db/schema";
import { logger } from "./logger";

const clubs = [
  {
    name: "Design & Innovation Society",
    shortName: "DIS",
    category: "Innovation",
    description: "A studio for students who turn campus problems into useful, beautiful solutions.",
    mission: "Build a culture of making through design sprints, workshops, and founder talks.",
    color: "#f07c5c",
    officeLocation: "Student Activity Centre · Room 204",
    meetingSchedule: "Wednesdays · 5:30 PM",
    eligibility: "Open to all undergraduate and postgraduate students. No prior design experience needed.",
    membershipStatus: "Open",
    memberCount: 184,
    contactEmail: "hello@dis-campus.edu",
    facultyAdvisor: "Dr. Meera Shah",
    roles: [
      { title: "Design Lead", responsibility: "Guide visual systems and mentor project teams.", openings: 2 },
      { title: "Community Manager", responsibility: "Welcome members and coordinate weekly studio sessions.", openings: 3 },
      { title: "Content Writer", responsibility: "Tell the story of projects across campus channels.", openings: 4 },
    ],
  },
  {
    name: "The Campus Chronicle",
    shortName: "TCC",
    category: "Media",
    description: "Independent student journalism covering the people, ideas, and decisions shaping campus.",
    mission: "Make campus information clear, accountable, and worth reading.",
    color: "#4f7cac",
    officeLocation: "Arts Block · Room 108",
    meetingSchedule: "Mondays · 6:00 PM",
    eligibility: "Students from any year or discipline. A writing sample is helpful but not required.",
    membershipStatus: "By application",
    memberCount: 72,
    contactEmail: "editor@campuschronicle.edu",
    facultyAdvisor: "Prof. Arjun Menon",
    roles: [
      { title: "Staff Reporter", responsibility: "Research and publish stories from campus life.", openings: 6 },
      { title: "Photo Editor", responsibility: "Shape the visual language of weekly coverage.", openings: 1 },
    ],
  },
  {
    name: "A cappella Collective",
    shortName: "AC",
    category: "Arts & Culture",
    description: "A close-knit vocal collective performing contemporary, classical, and regional music.",
    mission: "Make ambitious music together and make live performance feel accessible to everyone.",
    color: "#8d6e63",
    officeLocation: "Cultural Centre · Studio 3",
    meetingSchedule: "Tuesdays & Thursdays · 7:00 PM",
    eligibility: "Open auditions for all students. Commitment to two rehearsals per week is expected.",
    membershipStatus: "Open",
    memberCount: 31,
    contactEmail: "sing@ac-campus.edu",
    facultyAdvisor: "Ms. Nandita Rao",
    roles: [
      { title: "Vocalist", responsibility: "Rehearse and perform the seasonal setlist.", openings: 8 },
      { title: "Music Director", responsibility: "Arrange music and lead rehearsals.", openings: 1 },
    ],
  },
  {
    name: "Women in Computing",
    shortName: "WIC",
    category: "Technology",
    description: "A peer-led community for women and allies learning, building, and finding their next opportunity.",
    mission: "Create a more welcoming path into technology through peer learning and mentorship.",
    color: "#9b72cf",
    officeLocation: "Computer Centre · Lab 2",
    meetingSchedule: "Fridays · 4:00 PM",
    eligibility: "Open to students of all years. Women and gender minorities are especially encouraged to join.",
    membershipStatus: "Open",
    memberCount: 216,
    contactEmail: "join@wic-campus.edu",
    facultyAdvisor: "Dr. Ritu Kapoor",
    roles: [
      { title: "Workshop Facilitator", responsibility: "Host practical sessions for beginner and advanced learners.", openings: 5 },
      { title: "Industry Liaison", responsibility: "Coordinate mentor and speaker relationships.", openings: 2 },
    ],
  },
  {
    name: "Public Policy Forum",
    shortName: "PPF",
    category: "Social Impact",
    description: "A student forum for structured debate, policy research, and conversations across perspectives.",
    mission: "Help students engage with public questions thoughtfully and constructively.",
    color: "#3d8b78",
    officeLocation: "Humanities Block · Room 312",
    meetingSchedule: "Thursdays · 5:00 PM",
    eligibility: "Open to all students interested in policy, governance, and civic life.",
    membershipStatus: "Open",
    memberCount: 98,
    contactEmail: "forum@ppf-campus.edu",
    facultyAdvisor: "Prof. Sameer Iyer",
    roles: [
      { title: "Research Associate", responsibility: "Prepare briefs and backgrounders for forum discussions.", openings: 4 },
      { title: "Event Moderator", responsibility: "Facilitate respectful, high-quality public conversations.", openings: 2 },
    ],
  },
];

const events = [
  {
    title: "Design Sprint: Fix a Campus Friction",
    clubIndex: 0,
    category: "Workshop",
    date: "2026-09-12",
    startTime: "10:00 AM",
    endTime: "1:00 PM",
    venue: "Innovation Lab · Main Building",
    description: "A hands-on sprint where small teams identify one campus friction and prototype a better experience in three hours.",
    entryFee: "0",
    registrationDeadline: "2026-09-11",
    registrationCriteria: "Open to all students. Bring a laptop if possible.",
    dutyLeave: 1,
    seatsLeft: 38,
    registrationUrl: "#register",
    color: "#f07c5c",
  },
  {
    title: "Open Mic: New Voices",
    clubIndex: 2,
    category: "Performance",
    date: "2026-09-13",
    startTime: "6:30 PM",
    endTime: "8:30 PM",
    venue: "Amphitheatre",
    description: "An evening of music, poetry, and short-form performance from students across campus.",
    entryFee: "150",
    registrationDeadline: "2026-09-12",
    registrationCriteria: "Anyone may attend. Performers must submit a three-minute audition clip.",
    dutyLeave: 0,
    seatsLeft: 94,
    registrationUrl: "#register",
    color: "#8d6e63",
  },
  {
    title: "Build Night: Ship Your First App",
    clubIndex: 3,
    category: "Technology",
    date: "2026-09-16",
    startTime: "5:00 PM",
    endTime: "9:00 PM",
    venue: "Computer Centre · Lab 1",
    description: "Pair up, learn the basics, and leave with a tiny working app. Mentors will be available throughout.",
    entryFee: "0",
    registrationDeadline: "2026-09-15",
    registrationCriteria: "Open to all students. Beginners are welcome.",
    dutyLeave: 1,
    seatsLeft: 21,
    registrationUrl: "#register",
    color: "#9b72cf",
  },
  {
    title: "Policy in Practice: City Futures",
    clubIndex: 4,
    category: "Talk",
    date: "2026-09-18",
    startTime: "4:00 PM",
    endTime: "6:00 PM",
    venue: "Senate Hall",
    description: "A public conversation with urban practitioners about the choices that shape life in growing cities.",
    entryFee: "0",
    registrationDeadline: "2026-09-17",
    registrationCriteria: "Open to all students and faculty.",
    dutyLeave: 1,
    seatsLeft: 57,
    registrationUrl: "#register",
    color: "#3d8b78",
  },
];

export async function ensureCampusSeeded() {
  const [{ value: clubCount }] = await db.select({ value: count() }).from(clubsTable);
  if (clubCount > 0) return;

  const insertedClubs = await db.insert(clubsTable).values(clubs).returning({ id: clubsTable.id });
  await db.insert(eventsTable).values(
    events.map(({ clubIndex, ...event }) => ({
      ...event,
      clubId: insertedClubs[clubIndex]?.id ?? insertedClubs[0]!.id,
    })),
  );
  logger.info({ clubs: insertedClubs.length, events: events.length }, "Seeded campus hub demo data");
}